### PR TITLE
[WIP] Implement serialization of metadata

### PR DESCRIPTION
**Pull request by rubdos**
Regarding #28, I tried something and it works...

I only implemented serialization for now, as my application doesn't use the deserialization of metadata yet. It soon will, probably, so then I'll implement the other way.

You can already give me C&C on this implementation, I'll happily change what's on your mind.

### CODE REVIEW

**Comment by rubdos** [comment]
Regarding CI:

```
./marshmallow_jsonapi/__init__.py:7:1: E402 module level import not at top of file
./marshmallow_jsonapi/schema.py:149:5: E266 too many leading '#' for block comment
./examples/flask_example.py:3:1: E266 too many leading '#' for block comment
./examples/flask_example.py:19:1: E266 too many leading '#' for block comment
./examples/flask_example.py:39:1: E266 too many leading '#' for block comment
./examples/flask_example.py:41:1: E402 module level import not at top of file
./examples/flask_example.py:42:1: E402 module level import not at top of file
./examples/flask_example.py:43:1: E402 module level import not at top of file
./examples/flask_example.py:99:1: E266 too many leading '#' for block comment
```

`flake8` crashes, and it's not even on my additions.

**Comment by sloria** [comment]
Thanks for the PR. I've fixed the flake errors on the `dev` branch. They popped up after the latest update to `pep8`.

How is this different from using a `Dict` field that is `dump_only`?

**Comment by rubdos** [comment]
At the moment, there is no difference, but I'd like to implement deserialization too - otherwise receiving metadata will not work.

I'll rebase this branch on `dev`, so that the CI errors go away :)

**Comment by hirecom** [comment]
@sloria Is there an update to this?  If it's not going to be made available can you please explain how making a Dict fixes this?  I tried adding 

meta = fields.Dict({'test':1}) but this adds to each attribute, where we need it as a sibling of the data node.

**Comment by RazerM** [comment]
`fields.Dict` isn't going to work since it would end up within the `attributes` key. A `fields.Metadata` type makes sense to hoist that up as a sibling to `attributes`. This also means a schema can contain a normal attribute named `meta` (which isn't disallowed, if I'm reading the spec correctly.

**Comment by rubdos** [comment]
@Sam-Onella, for if you didn't notice, @RazerM continues this work in #56.

**Pull request closed without merging**
