### PR TITLE
Add support for resource meta object

### LINKED ISSUE #107: Document vs Root Meta Information
In my project I was making use of the Meta field type to include resource object level meta information about the object. This was especially important when the primary data was a list of resource objects.

```"python"
{'data': [{'attributes': {'name': 'Impossible Stand'},
          'id': '21',
          'links': {'self': '/persons/21'},
          'meta': {'modified_at': '2017-08-14T17:50:19+00:00'},
          'relationships': {'children': {'links': {'related': '/persons/21/children',
                                                   'self': '/persons/21/relationships/children'}},
                            'parent': {'links': {'related': '/persons/21/parent',
                                                 'self': '/persons/21/relationships/parent'}}},
          'type': 'persons'},
         {'attributes': {'name': 'Carry Cool'},
          'id': '22',
          'links': {'self': '/persons/22'},
          'meta': {'modified_at': '2017-08-14T17:50:19+00:00'},
          'relationships': {'children': {'links': {'related': '/persons/22/children',
                                                   'self': '/persons/22/relationships/children'}},
                            'parent': {'links': {'related': '/persons/22/parent',
                                                 'self': '/persons/22/relationships/parent'}}},
          'type': 'persons'}],
'links': {'self': '/persons/20/children'}}
```

#95 broke my build and makes it impossible to include specific meta data about a resource object in the serialized data. I understand that there is a need for both types of meta information, but I am not sure how to go about addressing both needs in a way that is applicable to all use cases.

Any advice about how to proceed would be welcome.

### PR DESCRIPTION
**Pull request by scottwernervt**
Closes #107.

New field, `fields.MetaResource`, is for non-standard meta-information about a resource that can not be represented as an attribute or relationship on the resource's object.

```python
from marshmallow_jsonapi import Schema, fields

class AuthorSchema(Schema):
    id = fields.Str(dump_only=True)
    name = fields.Str()

    resource_meta = fields.MetaResource()
    meta = fields.Meta()

    class Meta:
        type_ = 'people'
        strict = True

author = {'name': 'Alice', 'resource_meta': {'active': True}, 'meta': { 'page': 1}}
AuthorSchema().dump(author)
# {
#     "data": {
#         "type": "people",
#         "meta": {
#             "active": true
#         },
#         "attributes": {
#             "name": "Alice"
#         }
#     },
#     "meta": {
#         "page": 1
#     }
# }
```

### CODE REVIEW

**Comment by sloria** [comment]
This feature makes sense. Perhaps `ResourceMeta` is a more natural name, though. Other than that, I don't see any blockers to merging.

**Comment by rgant** [comment]
Looks acceptable to me. 

We have changed the meaning of the `Meta` field type in this version and I wonder about resolving that backwards incompatible change. Would it be better to have two different `Meta` field types (`ResourceMeta` & `TopMeta`)? I don't think it's critical to address this at this stage because it doesn't seem like there are many people using the `meta` key in JSONAPI.

I also think that I would like to consider adding some test cases for when the primary data key is an array of resource objects with meta information. @scottwernervt Do you expect that this change will handle a load many=True situation?

My two comments above are more for the future and I don't think they need to hold up merging this ticket. But I wanted to see if anyone was interested in discussing them.

**Comment by scottwernervt** [comment]
@sloria I will rename the field to `ResourceMeta` and `Meta` to `DocumentMeta`.

@rgant 
> Would it be better to have two different Meta field types (ResourceMeta & TopMeta)?

I didn't want to break current usage of the `Meta` field but to be consistent, it should be  `DocumentMeta`. 

> I also think that I would like to consider adding some test cases for when the primary data key is an array of resource objects with meta information.

I will add a test case for dumping with `many=True`.

> Do you expect that this change will handle a load many=True situation?

Loading document and resource meta data is broken. I will look into it.

**Comment by sloria** [comment]
@scottwernervt `ResourceMeta` and `DocumentMeta` sound good. Perhaps we should keep `Meta` around and raise a DeprecationWarning.

**Comment by rgant** [comment]
Great call on depreciating Meta @sloria.

This looks great to merge in now to me.

**Comment by scottwernervt** [comment]
If everything looks good I will go ahead and merge the pull request. Thanks for the feedback!

**Review by sloria — APPROVED** [review]
Looks great! Thanks for being thorough with tests and docs.

**Pull request merged**
