### PR TITLE
Add Flask-specific schema to generate self links from view names

### PR DESCRIPTION
**Pull request by asteinlein**
Instead of having to hard-code self URL links using `self_url`,
`self_url_kwargs` and `self_url_many`, users of Flask can use the new
Flask-specific schema and use `self_view`, `self_view_kwargs` and
`self_view_many` instead. This takes view names instead which generates
URLs from the Flask views.

Includes updated documentation (with some minor cleanups) and tests.

### CODE REVIEW

**Comment by asteinlein** [comment]
Any possibility of getting this merged and/or feedback on? :)

**Comment by sloria** [comment]
Sorry for the long delay on this. I will try to get this reviewed and merged this weekend. Thanks for your patience.

**Comment by sloria** [comment]
Looks good!  I'll cut a release shortly.

**Comment by rgant** [comment]
I've found an issue with this change. According to the [spec](http://jsonapi.org/format/#document-links) links objects cannot be `None`.

> The value of each links member MUST be an object (a “links object”).
> Each member of a links object is a “link”. A link MUST be represented as either:
> * a string containing the link’s URL.
> * an object (“link object”) which can contain the following members:
>   * href: a string containing the link’s URL.
>   * meta: a meta object containing non-standard meta-information about the link.

The [change to `get_top_level_links`](https://github.com/marshmallow-code/marshmallow-jsonapi/commit/5e574f0dc25d635fb91c3975f91a06df1270b5ec#diff-b7695ff9c3cc7a719a2b771764c10302L288) in this changeset set breaks `wrap_response` because that function expects to get back a [`falsey` value from `get_top_level_links`](https://github.com/marshmallow-code/marshmallow-jsonapi/blob/5e574f0dc25d635fb91c3975f91a06df1270b5ec/marshmallow_jsonapi/schema.py#L305) if there aren't any links defined. 

The current code results in schema.dump like: `'links': {'self': None}` where self_urls aren't defined for the schema. I don't think this follows the spec.

I plan to add a fix to this in my (under development) pull request for #58.

**Pull request merged**
