### PR TITLE
FlaskRelationship: handle `BuildError` for empty relationship on url generation

### PR DESCRIPTION
**Pull request by floqqi**
This should resolve issue #24.

### CODE REVIEW

**Comment by jo-tham** [comment]
Thanks! Looks good. We'll see what @sloria has to say.

**Comment by sloria** [comment]
Thanks for the PR. 

The JSON API spec doesn't seems to allow for `null` values for `links` members:

> Where specified, a links member can be used to represent links. The value of each links member MUST be an object (a "links object").

Source: http://jsonapi.org/format/#document-links

Perhaps the correct thing to do is to exclude the links object altogether for empty relationships.

**Comment by floqqi** [comment]
Now it should be compatible with the JSON API spec :+1:

**Comment by sloria** [comment]
Thanks!

**Pull request merged**
